### ISSUE TITLE
Not compatible with IE9

### ISSUE THREAD

**Issue by mariepw** [paulcollett/react-masonry-css#14]
Hello, 
Thanks for your work and your component :) it is really interesting.. 
But the documentation says that it is IE9+ compatible, whereas it is said to use `display: flex` which is not supported for IE9.
Did I misunderstand something?? 
Thanks a lot!

**Comment by paulcollett** [comment]
If you have the option to use "autoprefixer" (https://autoprefixer.github.io/) plugin when compiling your css, the IE9 compatible flexbox rules will automatically be added for you. Otherwise just paste the css into the generater at the link above. Hope that works for you!

**Comment by paulcollett** [comment]
Oh apologies, you are correct! I'll get the readme updated. If you're needing IE9 support, it should be as simple as replacing flexbox with floats to control the layout. Something like this:

```css
.my-masonry-grid {
  margin-left: -30px; // gutter size offset
}
.my-masonry-grid:after { // "clearfix" technique
   content: '';
   display: block;
   clear: both;
}
.my-masonry-grid_column {
  float: left;
}
```
